# Generated by Django 4.2.23 on 2025-07-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IzipayCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Configuración Principal', max_length=100)),
                ('merchant_code', models.CharField(max_length=20, verbose_name='Código del Comercio')),
                ('api_key', models.CharField(max_length=100, verbose_name='Clave API (Botón de Pagos)')),
                ('hash_key', models.CharField(max_length=100, verbose_name='Clave HASH')),
                ('public_key', models.TextField(verbose_name='Clave pública Izipay')),
                ('return_url', models.URLField(max_length=500, verbose_name='URL de redirección')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
