# Generated by Django 4.2.23 on 2025-07-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izipay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionIdCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.BigIntegerField(default=100000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'izipay_transaction_counter',
            },
        ),
        migrations.RemoveField(
            model_name='izipaycredential',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='izipaycredential',
            name='nombre',
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='hash_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='merchant_code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='public_key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='return_url',
            field=models.URLField(),
        ),
    ]
