# Generated by Django 4.2.23 on 2025-07-15 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izipay', '0002_transactionidcounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izipaycredential',
            name='public_key',
            field=models.CharField(max_length=1055),
        ),
    ]
