# Generated by Django 5.2.4 on 2025-07-15 03:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izipay', '0003_alter_izipaycredential_public_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzipayTransactionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_transaction_id', models.PositiveIntegerField(default=100009, help_text='Último ID de transacción generado. Se incrementa automáticamente.', verbose_name='ID de Transacción Actual')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contador de Transacciones Izipay',
                'verbose_name_plural': 'Contadores de Transacciones Izipay',
            },
        ),
        migrations.DeleteModel(
            name='TransactionIdCounter',
        ),
        migrations.AddField(
            model_name='izipaycredential',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 7, 15, 3, 58, 45, 393399, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='izipaycredential',
            name='nombre',
            field=models.CharField(default='Configuración Principal', max_length=100),
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='api_key',
            field=models.CharField(max_length=100, verbose_name='Clave API (Botón de Pagos)'),
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='hash_key',
            field=models.CharField(max_length=100, verbose_name='Clave HASH'),
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='merchant_code',
            field=models.CharField(max_length=20, verbose_name='Código del Comercio'),
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='public_key',
            field=models.TextField(verbose_name='Clave pública Izipay'),
        ),
        migrations.AlterField(
            model_name='izipaycredential',
            name='return_url',
            field=models.URLField(max_length=500, verbose_name='URL de redirección'),
        ),
    ]
