# Generated by Django 5.2.4 on 2025-07-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izipay', '0004_izipaytransactioncounter_delete_transactionidcounter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='izipaytransactioncounter',
            name='current_transaction_id',
            field=models.PositiveIntegerField(default=100010, help_text='Último ID de transacción generado. Se incrementa automáticamente.', verbose_name='ID de Transacción Actual'),
        ),
    ]
