# Generated by Django 5.2.4 on 2025-07-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('izipay', '0005_alter_izipaytransactioncounter_current_transaction_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('shopify_order_id', models.CharField(blank=True, max_length=50, null=True)),
                ('order_number', models.CharField(max_length=100)),
                ('payment_link_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_link_url', models.URLField(blank=True, null=True)),
                ('payment_link_state', models.CharField(choices=[('1', 'GENERADO'), ('3', 'TERMINADO_EXITO'), ('4', 'TERMINADO_ERROR'), ('5', 'EXPIRADO'), ('6', 'DESACTIVADO')], default='1', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PEN', max_length=3)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook_received_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'izipay_payment_transactions',
            },
        ),
        migrations.AddField(
            model_name='izipaycredential',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
