# Generated by Django 5.2.4 on 2025-07-13 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopifycredential',
            name='store_url',
            field=models.URLField(blank=True, help_text='URL completa de la tienda', max_length=500, null=True),
        ),
    ]
