# Generated by Django 5.2.4 on 2025-07-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopify_order_id', models.BigIntegerField(blank=True, help_text='ID de la orden generada en Shopify.', null=True, unique=True)),
                ('izipay_order_id', models.CharField(blank=True, help_text='ID de la orden generada en Izipay.', max_length=255, null=True)),
                ('status', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, help_text='Estado actual de la orden.')),
                ('izipay_payment_url', models.URLField(blank=True, help_text='URL de pago generada por Izipay.', max_length=512, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Orden de Checkout',
                'verbose_name_plural': 'Órdenes de Checkout',
                'ordering': ['-created_at'],
            },
        ),
    ]
