# Generated by Django 5.2.4 on 2025-07-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idord_shp', models.CharField(blank=True, max_length=255, null=True)),
                ('idord_izi', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('estado', models.IntegerField(choices=[(1, 'Iniciado'), (2, 'Creado en Shopify'), (3, 'Link de pago generado'), (4, 'Pagado'), (5, 'Error')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
